config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get '/home/about', to: 'homes#about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def index
    @book = Book.new
    @books = Book.all
     @user = current_user

  end

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @user = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book.id)
    else
      #renderについて
      @user = current_user
      
      @books = Book.all
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end


  private
  def book_params
    params.require(:book).permit(:title, :body,)
  end

def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to '/books'
    end
end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
 def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome! You have signed up successfully."
      redirect_to user_path(current_user)
    else
      render :users
    end
 end
  
  def index
    @users = User.all
    @book_new = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @book_new = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] ="You have updated user successfully."
       redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new-book.html.erb
<h2 class="mt-3">New book</h2>
<% if book.errors.any? %>
<%= book.errors.count %>error prohibited this obj from being saved:
<ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
</ul>
<% end %>


	    <%= form_with model: book do |f| %>
	     <h4>Title</h4>
           <%= f.text_field :title %>

         <h4>Opinion</h4>
           <%= f.text_area :body %>

	          <%= f.submit 'Create Book', class: "btn btn-success"  %>
        <% end %>

app/views/books/_user-info.html.erb
<script src="https://kit.fontawesome.com/1b378e5738.js" crossorigin="anonymous"></script>
	    <h2>User info</h2>
	    <% if user.errors.any? %>
      <%= user.errors.count %>error prohibited this obj from being saved:
      <ul>
          <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
          <% end %>
      </ul>
      <% end %>
	    <table class='table'>
	      <tr>
	        <%= image_tag user.get_profile_image(100,100) %>
	      </tr>
	      <tr>
	        <th>name</th>
	        <th><%= user.name %></th>
	      </tr>
	      <tr>
	        <th>introduction</th>
	        <th><%= user.introduction %></th>
	      </tr>
	    </table>


            <p><%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-lg" do %>
               <i class="fa-solid fa-user-gear"></i>
	           <% end %>
	        </p>

app/views/books/edit.html.erb
<script src="https://kit.fontawesome.com/1b378e5738.js" crossorigin="anonymous"></script>
<header>
<div class='container px-5 px-sm-0'>
	<div class='row'>
	  <div class='offset-md-4 col-md-8'>
<h2>Editing Book</h2>
<% if @book.errors.any? %>
<%= @book.errors.count %>error prohibited this obj from being saved:
<ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
</ul>
<% end %>

<%= form_with model: @book do |f| %>
<table>
<tr>
 <td> <label for="inputTitle">Title</label></td>
</tr>  
<tr>
  <td><%= f.text_field :title, id: "inputTitle" %></td>
</tr>  
</table>
<table>
<tr>
  <td><label for="inputOpinion">Opinion</label></td>
</tr>
<tr>
 <td><%= f.text_area :body, id: "inputOpinion" %> </td> 
</tr>
<tr>
  <td><%= f.submit "Update Book", class: "btn btn-secondary" %></td>
</tr>
</table>
  
<% end %>
<%=link_to 'Show', book_path(@book.id) %> | <%=link_to 'Back', "/books" %>
</div>
</div>
</div>

app/views/books/index.html.erb
<script src="https://kit.fontawesome.com/1b378e5738.js" crossorigin="anonymous"></script>
<header>
<!--部分テンプレート-->
<div class='container px-5 px-sm-0'>
	<div class='row'>
	  <div class='col-md-3'>
	  <%= render 'books/user-info', user: @user %>
	  <%= render 'books/new-book', book: @book %>
	  </div>
	  <div class='col-md-8 offset-md-1'>
	    <h2>Books</h2>
	    <table class='table table-hover table-inverse'>
	      <thead>
	        <tr>
	          <th></th>
	          <th>Title</th>
	          <th>Opinion</th>
	          <th colspan="3"></th>
	        </tr>
	      </thead>
	      <tbody>
	      	<% @books.each do |book| %>
	      	 <tr>
	      	  <td><%= link_to (image_tag book.user.get_profile_image(100,100)), user_path(book.user) %></td>

	      	  <td><%= link_to book.title, book_path(book) %></td>

            <td><%= book.body %></td>
	      	 </tr>
	      	<% end %>
	      </tbody>
	    </table>
	  </div>
	</div>
</div>

app/views/books/show.html.erb
<script src="https://kit.fontawesome.com/1b378e5738.js" crossorigin="anonymous"></script>
<div>
  <%= flash[:notice] %>
</div>

<!--部分テンプレート-->
<div class='container px-5 px-sm-0'>
	<div class='row'>
	  <div class='col-md-3'>


<%= render 'books/user-info', user: @user %>
<%= render 'books/new-book', book: @book_new %>

    </div>
<div class='col-md-8 offset-md-1'>
	    <h2>Book detail</h2>
	    <table class='table table-hover table-inverse'>

	      <tbody>

	      	 <tr>
	      	  <td><%= link_to (image_tag @book.user.get_profile_image(100,100)), user_path(@book.user) %>
	      	      <%= link_to @book.user.name, user_path(@book.user) %>
	      	  </td>

	      	  <td><%= link_to @book.title, book_path(@book) %></td>

              <td><%= @book.body %></td>

              <td>
              <% if @book.user == current_user %>	
               <%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-secondary" %>
              <% end %>
              </td>

              <td>
              	<% if @book.user == current_user %>
                 <%= link_to "Destroy", book_path(@book.id), class: "btn btn-secondary", method: :delete, "data-confirm" => "本当に消しますか？" %>
                <% end %> 
              </td>
	      	 </tr>

	      </tbody>
	    </table>
</div>
	</div>
</div

app/views/homes/about.html.erb
<script src="https://kit.fontawesome.com/1b378e5738.js" crossorigin="anonymous"></script>
 <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!
      </h1>
    </div>

app/views/homes/top.html.erb
<script src="https://kit.fontawesome.com/1b378e5738.js" crossorigin="anonymous"></script>
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>in <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions<p>
      <p>about various books!</p>
      
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <div class="container">
       <a class="navbar-brand" href="/"><span>Bookers</span></a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <script src="https://kit.fontawesome.com/1b378e5738.js" crossorigin="anonymous"></script>
            <li>
              <%= link_to user_path(current_user), class:"nav-link text-light" do%>
               <i class="fa-solid fa-house"></i> Home
              <% end %>
            </li>
            <li>
               <%= link_to users_path, class:"nav-link text-light" do%>
                <i class="fa-solid fa-users"></i> Users
               <% end %>
            </li>
            <li>
               <%= link_to books_path, class:"nav-link text-light" do%>
                <i class="fa-solid fa-book-open"></i> Books
               <% end %>
            </li>
            <li>
               <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do%>
                <i class="fa-solid fa-right-from-bracket"></i> Log out
               <% end %>
            </li>
          <% else %>
           <script src="https://kit.fontawesome.com/1b378e5738.js" crossorigin="anonymous"></script>
            <li>
              <%= link_to root_path, class:"nav-link text-light" do%>
               <i class="fa-solid fa-house"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path, class:"nav-link text-light" do %>
               <i class="fa-solid fa-link"></i> About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
               <i class="fa-solid fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class:"nav-link text-light" do %>
               <i class="fa-solid fa-right-to-bracket"></i> Log in
              <% end %>
            </li>
          <% end %>
        </ul>
       </div>
      </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/edit.html.erb
<div class='container px-5 px-sm-0'>
	<div class='row'>
	  <div class='offset-md-4 col-md-8'>
<% if @user.errors.any? %>
<%= @user.errors.count %>error prohibited this obj from being saved:
<ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
</ul>
<% end %>

<h2>User info</h2>
<%= form_with model: @user do |f| %>
<table>
 <tr> 
<td><label for="inputName">Name</label></td> 
 </tr>
 <tr>
 <td><%= f.text_field :name, autofocus: true, id:"inputName" %></td>
 </tr>
</table>
<table>
 <tr>
 <td><label for="inputImage">Image</label></td>
 </tr> 
 <tr>
 <td><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></td>
 </tr> 
</table>
<table>
 <tr>  
 <td><label for="inputIntroduction">Introduction</label></td>
 </tr> 
 <tr>
 <td><%= f.text_field :introduction, id: "inputIntroduction" %></td>
 </tr> 
</table>  
  <%= f.submit "Update User", class: "btn btn-secondary" %>

<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<script src="https://kit.fontawesome.com/1b378e5738.js" crossorigin="anonymous"></script>
<!--部分テンプレート-->
<div class='container px-5 px-sm-0'>
	<div class='row'>
	  <div class='col-md-3'>


<%= render 'books/user-info', user: @user %>

<%= render 'books/new-book', book: @book_new %>
	  </div>

<div class='col-md-8 offset-md-1'>
	    <h2>Users</h2>
	    <table class='table table-hover table-inverse'>
	      <thead>
	        <tr>
	          <th>image</th>
	          <th>name</th>
	          <th></th>
	          <th colspan="3"></th>
	        </tr>
	      </thead>
	      <tbody>
	      	<% @users.each do |user| %>
	      	 <tr>
	      	   <td><%= image_tag user.get_profile_image(100,100) %></td>

	      	   <td><%= user.name %></td>

	      	   <td><%= link_to "Show", user_path(user.id) %></td> <!--reiauto-->


	      	 </tr>
	      	<% end %>
	      </tbody>
	    </table>
</div>

		</div>
</div>

app/views/users/show.html.erb
<script src="https://kit.fontawesome.com/1b378e5738.js" crossorigin="anonymous"></script>
<div>
  <%= flash[:notice] %>
</div>

<div class='container px-5 px-sm-0'>
	<div class='row'>
	  <div class='col-md-3'>

<%= render 'books/user-info', user: @user %>


	    
<%= render 'books/new-book', book: @book_new %>
	   </div>
<div class='col-md-8 offset-md-1'>  
	    <h2>Books</h2>
	    <table class='table table-hover table-inverse'>
	      <thead>
	        <tr>
	          <th></th>
	          <th>Title</th>
	          <th>Opinion</th>
	          <th colspan="3"></th>
	        </tr>
	      </thead>
	      <tbody>
	      	<% @books.each do |book| %>
	      	 <tr>
	      	  <td><%= link_to (image_tag book.user.get_profile_image(100,100)), user_path(@user.id) %></td>
	      	  
	      	  <td><%= link_to book.title, book_path(book) %></td>
   
            <td><%= book.body %></td>
	      	 </tr>
	      	<% end %> 
	      </tbody>
	    </table>
	  </div>


	</div>	  
</div>	